name: Trigger auto deployment for adproject-app-20250808112415

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/adproject-app-20250808112415-AutoDeployTrigger-0ddc2a0f-4116-48ac-aa6e-ead60d4c773c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ADPROJECTAPP20250808112415_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ADPROJECTAPP20250808112415_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ADPROJECTAPP20250808112415_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: adproject20250808112953.azurecr.io
          registryUsername: ${{ secrets.ADPROJECTAPP20250808112415_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ADPROJECTAPP20250808112415_REGISTRY_PASSWORD }}
          containerAppName: adproject-app-20250808112415
          resourceGroup: adproject-app-20250808112415ResourceGroup
          imageToBuild: adproject20250808112953.azurecr.io/adproject-app-20250808112415:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


